version: '3.8'

services:
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   command: python myWSGI.py
  #   volumes:
  #     - ./app/static:/home/app/static
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./env.dev
  #   networks:
  #     - webservice-network
  #     - pythonframework-network

  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/home/app/static
    ports:
      - 8888:80
    # depends_on:
    #   - app      
